### ISSUE TITLE
Allow alternate install sources for Pester

### ISSUE THREAD

**Issue by smurawski** [test-kitchen/kitchen-pester#1]
Support PowerShellGet, Chocolatey, and host file system as well as the default PSGet.

**Comment by gaelcolas** [comment]
#64 will support PowerShellGet, a nuget feed with PS modules, and the host file systems.
Chocolatey could be used by using lifecycle hooks.

**Comment by gaelcolas** [comment]
This can be closed.
You can either use lifecycle hooks in TK, copy from local to SUT, use a nugetv2 feed.
If what you copy to the SUT is a build script like in https://github.com/gaelcolas/Sampler, you can use PSDepend to install your dependencies, for instance using choco.

**Comment by gep13** [comment]
@gaelcolas sounds good.
