### ISSUE TITLE
Kitchen Pester YML override for Pester Location

### ISSUE THREAD

**Issue by beaudryj** [test-kitchen/kitchen-pester#12]
Due to wanting to change download location of pester, it would be nice to take control of the external dependency on my build server and specify a different location of the pester installation whether it is using nuget, or some other means to download.

**Comment by smurawski** [comment]
👍

**Comment by gaelcolas** [comment]
#64 will support specifying a nuget feed to install (download & unzip in `$PSHome/modules` path, install from a Gallery (PowerShellGet), and (not yet implemented) register or update PSRepositories.

**Comment by gaelcolas** [comment]
This one can be closed.
You can:
- copy pester from the local machine to the SUT (using `copy_folders`).
- install pester from a private repo
- skip the "built in" pester installation and make it available in some other way (i.e. lifecycle hooks)
- bootstrap pester from a nugetV2 feed.

Let me know if something is missing.

**Comment by gep13** [comment]
@gaelcolas thank you.
