### ISSUE TITLE
Possible to add the "helpers" logic from busser?

### ISSUE THREAD

**Issue by nhudacin** [test-kitchen/kitchen-pester#20]
I would love the ability to have a generic test file that ran over all my suites, in addition to the suite specific tests like in the current functionality. Poking around a bit, it looks like using busser supports this (undocumented feature)... https://github.com/test-kitchen/test-kitchen/pull/134

The commit referenced in #134 https://github.com/test-kitchen/test-kitchen/commit/7c495f44772073d70df5d67d1f5f4552c5d62138

Maybe I'll queue up a pull request.

**Comment by gaelcolas** [comment]
This has been merged years ago and can be closed.

**Comment by gep13** [comment]
@gaelcolas sounds like a plan.
