### ISSUE TITLE
Verify doesn't run Pester tests on Nano

### ISSUE THREAD

**Issue by rschiefer** [test-kitchen/kitchen-pester#25]
Running kitchen verify completes with no errors but it's not running any of my Pester tests.

Here is the full verify log: https://gist.github.com/rschiefer/92da5a9b7fd5a400b11e8ed2c5a9f68c

Here is my kitchen file: https://gist.github.com/rschiefer/589cc3b3db824a7fb71fd0a142f6b815

**Version info:**
Microsoft Windows [Version 10.0.14393]
Chef Development Kit Version: 1.2.22
chef-client version: 12.18.31kitchen version: 1.15.0
kitchen-hyperv (0.3.0)
kitchen-inspec (0.17.0)
kitchen-pester (0.7.1)
test-kitchen (1.16.0, 1.15.0)

**Comment by smurawski** [comment]
Thanks @rschiefer - I haven't tried it on Nano yet, but I'm planning to do some Nano work later this week, early next, so I'll dig in.

**Comment by rschiefer** [comment]
Cool. I'm willing to help if you can give me a little direction in troubleshooting.

**Comment by rschiefer** [comment]
False alarm, the real problem is I'm an idiot.  Changed the suite name in the kitchen.yml file but didn't update my test folder name.  Sorry for wasting your time.  

The good news is Nano works great with the HyperV driver, Kitchen, DSC and Pester!
