### ISSUE TITLE
Pester tests ignored

### ISSUE THREAD

**Issue by briceo** [test-kitchen/kitchen-pester#29]
I'm trying to use pester to write some test for test-kitchen, and I can't seem to get them to execute.  Here is the kitchen.yml I am using: https://gist.github.com/briceo/e327493212996e3162af6c6a298b2a7b

My test script (located: test\integration\default\pester\default.tests.ps1) just throws an exception on purpose so that I can verify that it is actually running.  When I run `kitchen verify` it appears that everything passes:

```
PS C:\repos\cookbook-base_server> kitchen verify
-----> Starting Kitchen (v1.23.2)
-----> Verifying <default-windows-2012r2>...
       Preparing files for transfer
       Preparing to copy supporting powershell modules.
       Preparing to copy files from C:/repos/cookbook-base_server/test/integration/default to the SUT.
       Installing from Github
       Transferring files to <default-windows-2012r2>
       Finished verifying <default-windows-2012r2> (0m19.37s).
-----> Kitchen is finished. (0m31.87s)
```

So it would appear that the test is not running (or I guess that the error is not being reported back?).

However, when I run `kitchen verify -l debug`, it appears that there is some issues installing pester in the SUT (or at least that's what it looks like to me): https://gist.github.com/briceo/b3b818107ec26495acd675eddb49ecc2

Have I not configured the `kitchen.yml` or the pester test correctly?

**Comment by briceo** [comment]
Ah ha!  I think I figured out what was going on.  This is an example of enforcing TLS1.2.  Recently (or not), Github has started enforcing TLS1.2 as the only protocol that is supported.  Unfortunately, Powershell does NOT default to TLS1.2

By adding
```
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
```
at https://github.com/test-kitchen/kitchen-pester/blob/master/lib/kitchen/verifier/pester.rb#L138 into the PsGet/Pester install block, things seem to work (meaning it ran my pester tests as expected).

Because the SUT may not be defaulted to TLS1.2, it seems like the install script(s) for PsGet and Pester should force TLS1.2 (it is as simple as putting the above line in the script before constructing the web client).

Would that be possible to do?
Also, would it be possible to have `kitchen-pester` fail when it can't actually install/run pester?

**Comment by briceo** [comment]
I went ahead an created a PR for at least forcing TLS1.2: https://github.com/test-kitchen/kitchen-pester/pull/30

**Comment by gaelcolas** [comment]
This has been merged (years ago) and can be closed.

**Comment by gep13** [comment]
@gaelcolas thanks for confirming.
