### ISSUE TITLE
BUG: kitchen-pester not working after upgrade to ChefDK 4.x

### ISSUE THREAD

**Issue by danielcbright** [test-kitchen/kitchen-pester#33]
### Problem
1. with Chef 4.0.6, I can't make it the kitchen-pester 0.8.0 work at all. it just can't find the gem for some reason

with Chef 3.11.3. kitchen-pester works fine 

there seems to be breaking changes with the latest chefdk that need to be addressed

**Comment by smurawski** [comment]
@danielcbright I just released 0.9.0 which should loosen up the dependencies to allow it to be loaded.  Let me know if that fixes things for you.

Thanks!

**Comment by danielcbright** [comment]
thanks @smurawski! will do!

**Comment by stuartpreston** [comment]
@danielcbright For some reason the packaging for 0.9.0 did not include everything required for the verifier to run. Steven gave me access to push up a new version (0.9.1) - please try and reopen this issue if there are still problems.

**Comment by gep13** [comment]
@stuartpreston happy to report that this is now working for me.  Thanks again for taking a look at this, really appreciate it!
