### ISSUE TITLE
CI/CD Build Package task failing due to Ruby version mismatch

### ISSUE THREAD

**Issue by vexx32** [test-kitchen/kitchen-pester#56]
# Expected Result:

CI runs and reports either successful or failing tests.

# Actual Result:

One of the CI agents falls over completely, apparently due to an issue with the available Ruby versions on that runner?

![image](https://user-images.githubusercontent.com/32407840/80239388-24aa9c80-862e-11ea-9447-bbb8442faa45.png)

Azure link: https://dev.azure.com/test-kitchen/41d5c926-6581-4f75-b03b-c87b3755b8cf/_build/results?buildId=348&view=logs&jobId=f1c12906-0b95-5937-a1e8-b8bed20e50bf

/cc @smurawski I see that 2.6.2 is the targeted Ruby version here; should we be a little less stringent and ask for just `2.6` or update it to `2.6.6` which the agent(s) apparently do have?

https://github.com/test-kitchen/kitchen-pester/blob/e5c9036416a699201117288f70c8ba72ec100f79/azure-pipelines.yml#L70-L79

**Comment by smurawski** [comment]
Resolved with https://github.com/test-kitchen/kitchen-pester/commit/4b13479a99786eff552582bd2e299706245ca1d9#diff-fec826feae04e51c0d94076385408bdc
