### ISSUE TITLE
Warnings about PowerShell execution policy when running tests

### ISSUE THREAD

**Issue by DecoyJoe** [test-kitchen/kitchen-pester#69]
## :ghost: Brief Description

When running Pester tests on Windows, `kitchen-pester` always writes the following warning:

```
WARNING: Set-ExecutionPolicy : Windows PowerShell updated your execution policy successfully, but the setting
is overridden by a policy defined at a more specific scope.  Due to the override, your shell will retain its
current effective execution policy of Bypass. Type "Get-ExecutionPolicy -List" to view your execution policy
settings. For more information please see "Get-Help Set-ExecutionPolicy".
At C:\windows\temp\winrm-elevated-shell-3c6fdc39-19f0-4d60-8062-0ce5782084e5.ps1:4 char:5
+     Set-ExecutionPolicy Unrestricted -force
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], SecurityException
    + FullyQualifiedErrorId : ExecutionPolicyOverride,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
```

I don't know what is setting the execution policy at a more specific scope, I assume it's Test Kitchen?

`kitchen-pester` should handle this scenario rather than show me a warning every time, of which I can't do anything about.

## Version

`1.0.0`

## Environment

Tested on:
* Windows Server 2012 R2
* Windows Server 2019

## Steps to Reproduce

Use `kitchen-pester` to run Pester 4 tests on a Windows platform.

## Expected Result

`kitchen-pester` properly handles setting or running tests with the proper execution policy when there are existing policies set at different scopes.

## Actual Result

I see the above warning on every test run.

**Comment by corbob** [comment]
Is there any particular reason that `kitchen-pester` doesn't use the scope of `Process`?

It seems that it's already set by Kitchen itself to `Bypass`:
![image](https://user-images.githubusercontent.com/30301021/151640539-08fef3df-c3a4-42a1-b695-24995a988126.png)
but it probably wouldn't hurt to set it in `kitchen-pester` as well (although my preference is `Bypass` instead of `Unrestricted`).

**Comment by smurawski** [comment]
It was set initially because the transport in Test-Kitchen didn't set that and supported earlier versions of powershell that didn't support Bypass.
