### ISSUE TITLE
Documentation Update Request: Testing

### ISSUE THREAD

**Issue by nhudacin** [test-kitchen/kitchen-pester#8]
Hey @smurawski how are you testing this? I would love to add a couple features, and work on any issues that come up. I use Pester for everything! And now that we have Test-Kitchen up and running, I can finally use the Kitchen-Pester plugin. 

I'm looking for a very high-level overview of how you test any changes to this module. Are you able to call this gem from a ruby shell? What would your typical workflow be to tweak the Invoke-Pester command? 

Thank you in advance!

**Comment by nhudacin** [comment]
I think I got it... 

I find the kitchen-pester gem installed on my workstation and made modifications there. Duh. Closing the issue as it's not needed anymore. Thank you!

**Comment by smurawski** [comment]
Actually this is a good point.  I'll document and add an option to customize the test command.

**Comment by gaelcolas** [comment]
From windows I test it using another project, once I built the Gem with the below script:

```PowerShell
chef gem build $PSScriptRoot/kitchen-pester.gemspec

rm -Force ~/appdata/local/chefdk/gem/ruby/*/cache/kitchen-pester-*.gem
rm -Force ~/appdata/local/chefdk/gem/ruby/*/specifications/kitchen-dsc-*.gemspec
rm -Force ~/appdata/local/chefdk/gem/ruby/*/gems/kitchen-pester-* -Recurse

chef gem install (gi $PSScriptRoot/kitchen-pester-*.gem).Name
Get-Date
```

It's true that better CI would be good though, happy to hear suggestions.

**Comment by corbob** [comment]
Not sure if it fulfills this request, but I added a [TESTING.md](https://github.com/test-kitchen/kitchen-pester/blob/main/TESTING.md) file since the PR template asked for it. Could probably use some more information, but it worked for the testing I wanted to do.
